import type { Metadata } from 'next';

import '@/app/globals.css';

import localFont from 'next/font/local';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import GlobalAlert from '@/components/common/GlobalAlert';
import ReactQueryProvider from '@/providers/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

const pretendard = localFont({
  src: '../static/fonts/Pretendard-Regular.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className="min-h-screen flex flex-col">
        <ReactQueryProvider>
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
          <GlobalAlert />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
